noirguilds:
  friendlyfire: false # If false, overrides all guild settings. If true or not set, allows group control (can be per player/area with flag)
  debug: false
  database:
    type: flatfile/mysql
    mysql:
      hostname: localhost
      port: 3306
      username: herp
      password: 'derp'
      database: foo
      prefix: bar_