noirguilds:
  initial-member-limit: 10
  upgrade:
    initial-cost: 10000
    multiplier: 1.5
  kill-money: 10
  db:
    host: localhost
    port: 3306
    username: noirguilds
    password: 'guilds'
    name: noirguilds
    prefix: guild