noirguilds:
  member-limit: 25
  kill-money: 10
  database:
    type: flatfile
    mysql:
      hostname: localhost
      port: 3306
      username: noirguilds
      password: 'guilds'
      database: noirguilds
      prefix: guild_