author: ZephireNZ
database: false
main: me.zephirenz.noirguilds.NoirGuilds
name: NoirGuilds
startup: postworld
version: ${version}
depend: [WGCustomFlags, ZephCore]
softdepend: [BankOfNoir]
commands:
    guild:
        description: Commands relating to NoirGuilds
        usage: See /guild help for help
    guilds:
        description: Guild information and statistics
        usage: See /guilds help for more
    grank:
        description: Create/edit/delete guild ranks
        usage: See /grank help for help
    g:
        description: Private guild chat
        usage: /g [your message here]
    ga:
        description: Private guild admin chat
        usage: /ga [your message here]
    gtp:
        description: teleport to another guild member
        usage: /gtp [player]
    gtphere:
        description: teleport another guild member to you
        usage: /gtphere [player]
    hq:
        description: "teleport to  or set your guild's HQ"
        usage: /hq (set)
permissions:
    noirguilds.create:
        description: Create a guild under own name
        default: op
    noirguilds.create.other:
        description: Create guild under anothers name
        default: op
    noirguilds.disband.other:
        description: Can disband another guild
        default: op
    noirguilds.reload:
        description: Reload plugin and config files
        default: op
    noirguilds.bank.other:
        description: Ability to see and edit other banks
        default: op